### ISSUE TITLE
No config file silently ignored

### ISSUE THREAD

**Issue by Roland0** [cedricbonhomme/pyHIDS#6]
Thanks for your work on pyHIDS it has inspired me.

While looking at your code (and using it) I noticed that [this](https://github.com/cedricbonhomme/pyHIDS/blob/6b90f3e385ae007217609d51e61242dce0c0a945/conf.py#L11-L15) try block will never raise an exception as the config.read() method silently fails ([by design](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.read)) and returns an empty list.

I've noticed a few similar issues around the config file, I'm writing a PR (or PRs) if you're happy with that :)

**Comment by cedricbonhomme** [comment]
Hi !

Indeed, it's partly intentional (and perhaps a touch of laziness on my part). I opted to let the user create their own config file using the provided example. However, I acknowledge that there's room for enhancement in this aspect. Clearly !
Therefore, I'm fully supportive of a pull request to address these improvements. :-)

Thank you !

**Comment by cedricbonhomme** [comment]
I close the ticket with this little change. But if you have other improvements concerning the loading of the configuration file, feel free to open a pull request.
